version: "2.0"

services: 
  dbcm:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password123123
      - MYSQL_DATABASE=cuantomeme
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password123123
  webapp:
    image: rdbarrientosa/cuantomemespring3
    depends_on:
      - dbcm
    ports:
      - 8080:8080

    links:
      - dbcm
    environment:
      - CMURL=dbcm
      - CMUSER=user
      - CMPASS=password123123
      - CMDB=cuantomeme
      - CMPORT=3306
  cuantomemeAngular:
    image: rdbarrientosa/cuantomemefrontend
    depends_on:
      - webapp
    ports:
      - 4200:80
    
